server:
  host: "0.0.0.0"
  port: "8080"

database:
  # For local development, using SQLite (no setup required)
  driver: "sqlite"
  dsn: "todoapp.db"
  
  # PostgreSQL configuration (for production)
  # host: "localhost"
  # port: "5432"
  # user: "todouser"
  # password: "todopassword"
  # dbname: "todoapp"
  # sslmode: "disable"

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expiry_hour: 24 